spidermonkey_78: pin python39
Because the configure script hasn't been update to work with Python 3.10
and never will. Spidermonkey 78 is EOL.

Traceback (most recent call last):
  File "/build/firefox-78.15.0/obj/../js/src/../../configure.py", line 25, in <module>
    from mozbuild.configure import (
  File "/build/firefox-78.15.0/python/mozbuild/mozbuild/configure/__init__.py", line 33, in <module>
    from mozbuild.util import (
  File "/build/firefox-78.15.0/python/mozbuild/mozbuild/util.py", line 760, in <module>
    class HierarchicalStringList(object):
  File "/build/firefox-78.15.0/python/mozbuild/mozbuild/util.py", line 785, in HierarchicalStringList
    class StringListAdaptor(collections.Sequence):
AttributeError: module 'collections' has no attribute 'Sequence'